/**
 * `nestToc` — turn a flat h2/h3 list (Astro's `MarkdownHeading` shape,
 * filtered to depth 2-3) into a parent/child tree for nested-list
 * rendering.
 *
 * The algorithm uses a stack to track the most recent open parent. A
 * heading becomes a child of the deepest open heading whose depth is
 * strictly less than its own; otherwise it sits at the root. This
 * handles the common markdown shape:
 *
 *   ## A
 *   ## B
 *   ### B.1
 *   ## C
 *
 * which renders as:
 *
 *   [A]
 *   [B]
 *     [B.1]
 *   [C]
 *
 * Sibling h3s (#### etc.) — anything deeper than h3 — are not
 * generated by the call sites (callers filter to h2/h3 upstream),
 * but the algorithm is depth-agnostic for the first three levels.
 */
export type TocItem = {
  depth: 2 | 3;
  slug: string;
  text: string;
  children: TocItem[];
};

/** Internal: a looser shape so callers can pass a subset of fields
 * or include any depth during testing. Output is always `TocItem`. */
type Flat = { depth: number; slug: string; text: string };

export function nestToc(flat: readonly Flat[]): TocItem[] {
  const root: TocItem[] = [];
  const stack: TocItem[] = [];

  for (const h of flat) {
    const node: TocItem = {
      depth: h.depth as 2 | 3,
      slug: h.slug,
      text: h.text,
      children: [],
    };
    // Pop anything that's not a strict ancestor of the current node.
    while (stack.length > 0 && stack[stack.length - 1].depth >= node.depth) {
      stack.pop();
    }
    if (stack.length === 0) {
      root.push(node);
    } else {
      stack[stack.length - 1].children.push(node);
    }
    stack.push(node);
  }
  return root;
}
